// Mechanical Murmuration — Barrel Cam Assembly
// Generated by generate_murmuration_cam.py
// Two barrel cams encoding Boids X and Y trajectories

// ─── PARAMETERS ─────────────────────────────────────
CAM_DIAMETER = 60.0;
CAM_LENGTH = 200.0;
SHAFT_BORE = 8.0;
GROOVE_DEPTH = 5.0;
NUM_BIRDS = 64;

// Spacing between cams on the shaft
CAM_GAP = 20;  // mm between cams
SHAFT_EXTENSION = 30;  // mm beyond each end

// Total shaft length
SHAFT_LEN = CAM_LENGTH * 2 + CAM_GAP + SHAFT_EXTENSION * 2;

// ─── TOGGLES ────────────────────────────────────────
SHOW_CAM_X = true;
SHOW_CAM_Y = true;
SHOW_SHAFT = true;
SHOW_FOLLOWERS = true;
SHOW_GUIDE_LINES = false;

// ─── QUALITY ────────────────────────────────────────
$fn = 48;

// ─── COLORS ─────────────────────────────────────────
CAM_X_COLOR = [0.85, 0.25, 0.25, 0.85];  // red
CAM_Y_COLOR = [0.25, 0.45, 0.85, 0.85];  // blue
SHAFT_COLOR = [0.7, 0.7, 0.7, 1.0];       // steel
FOLLOWER_COLOR = [0.3, 0.8, 0.3, 0.6];    // green

// ─── ASSEMBLY ───────────────────────────────────────

// Shaft
if (SHOW_SHAFT) {
    color(SHAFT_COLOR)
    translate([0, 0, -SHAFT_EXTENSION])
    cylinder(d=SHAFT_BORE - 0.1, h=SHAFT_LEN, $fn=24);
}

// Cam X (horizontal motion)
if (SHOW_CAM_X) {
    color(CAM_X_COLOR)
    import("murmuration_cam_x.stl", convexity=10);
}

// Cam Y (vertical motion) — offset along shaft
if (SHOW_CAM_Y) {
    color(CAM_Y_COLOR)
    translate([0, 0, CAM_LENGTH + CAM_GAP])
    import("murmuration_cam_y.stl", convexity=10);
}

// Follower positions (visualization only)
if (SHOW_FOLLOWERS) {
    groove_pitch = CAM_LENGTH / NUM_BIRDS;
    for (axis = [0, 1]) {
        z_offset = axis * (CAM_LENGTH + CAM_GAP);
        cam_color = axis == 0 ? CAM_X_COLOR : CAM_Y_COLOR;
        for (i = [0 : NUM_BIRDS - 1]) {
            z = z_offset + (i + 0.5) * groove_pitch;
            // Follower pin at 12 o'clock position
            color(FOLLOWER_COLOR)
            translate([0, CAM_DIAMETER/2 + 3, z])
            rotate([0, 90, 0])
            cylinder(d=1.0, h=8, center=true, $fn=12);
        }
    }
}

// Guide lines showing groove positions
if (SHOW_GUIDE_LINES) {
    groove_pitch = CAM_LENGTH / NUM_BIRDS;
    for (i = [0 : NUM_BIRDS - 1]) {
        z = (i + 0.5) * groove_pitch;
        color([1, 1, 0, 0.3])
        translate([0, 0, z])
        cylinder(d=CAM_DIAMETER + 10, h=0.2, $fn=48);
    }
}
