"""
CadQuery/build123d generation engine for Kinetic Forge Studio.

Executes Python CAD scripts generated by the chat agent in a sandboxed
subprocess. Captures output files (STEP, STL) and validates results.

This engine handles B-rep geometry generation from Python scripts using
either CadQuery or build123d APIs.
"""

import asyncio
import json
import logging
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

from app.config import settings
from app.middleware.cache import execution_cache, make_hash_key

logger = logging.getLogger(__name__)

# Timeout for CAD script execution (seconds)
SCRIPT_TIMEOUT = 120


@dataclass
class GenerationResult:
    """Result of executing a CAD generation script."""
    success: bool
    output_files: dict[str, Path] = field(default_factory=dict)  # format -> path
    error: str = ""
    stdout: str = ""
    stderr: str = ""
    execution_time: float = 0.0


@dataclass
class ValidationResult:
    """Result of validating a STEP file."""
    valid: bool
    body_count: int = 0
    face_count: int = 0
    volume: float = 0.0
    bounding_box: dict | None = None
    errors: list[str] = field(default_factory=list)


class CadQueryEngine:
    """
    Execute CadQuery/build123d Python scripts and capture output.

    Scripts are run in a subprocess for safety. Output STEP/STL files
    are written to a temp directory and then moved to the project's
    models directory.
    """

    async def generate(
        self,
        code: str,
        output_dir: Path,
        filename_base: str = "generated",
    ) -> GenerationResult:
        """
        Execute a CadQuery/build123d Python script.

        The script should assign its result to a variable named `result`.
        We append export logic that writes STEP and STL files.

        Args:
            code: Python script text (CadQuery or build123d).
            output_dir: Directory to write output files.
            filename_base: Base name for output files.

        Returns:
            GenerationResult with paths to generated files.
        """
        # Check execution cache before running
        cache_key = make_hash_key("cadquery_exec", code)
        cached = await execution_cache.aget(cache_key)
        if cached is not None:
            logger.debug("execution_cache HIT for code hash %s", cache_key[:12])
            return cached

        output_dir.mkdir(parents=True, exist_ok=True)
        step_path = output_dir / f"{filename_base}.step"
        stl_path = output_dir / f"{filename_base}.stl"

        # Wrap the user script with export logic
        wrapped_code = self._wrap_script(code, str(step_path), str(stl_path))

        # Write to temp file for subprocess execution
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as f:
            f.write(wrapped_code)
            script_path = f.name

        t0 = time.monotonic()
        try:
            proc = await asyncio.create_subprocess_exec(
                "python", script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=SCRIPT_TIMEOUT
            )
            elapsed = time.monotonic() - t0

            stdout = stdout_bytes.decode("utf-8", errors="replace")
            stderr = stderr_bytes.decode("utf-8", errors="replace")

            if proc.returncode != 0:
                return GenerationResult(
                    success=False,
                    error=f"Script failed (exit code {proc.returncode}): {stderr[:500]}",
                    stdout=stdout,
                    stderr=stderr,
                    execution_time=elapsed,
                )

            # Collect output files
            output_files = {}
            if step_path.exists() and step_path.stat().st_size > 0:
                output_files["step"] = step_path
            if stl_path.exists() and stl_path.stat().st_size > 0:
                output_files["stl"] = stl_path

            if not output_files:
                return GenerationResult(
                    success=False,
                    error="Script ran successfully but produced no output files.",
                    stdout=stdout,
                    stderr=stderr,
                    execution_time=elapsed,
                )

            result = GenerationResult(
                success=True,
                output_files=output_files,
                stdout=stdout,
                stderr=stderr,
                execution_time=elapsed,
            )
            # Cache successful results (keyed by code content)
            await execution_cache.aset(cache_key, result)
            logger.debug("execution_cache STORE for code hash %s", cache_key[:12])
            return result

        except asyncio.TimeoutError:
            return GenerationResult(
                success=False,
                error=f"Script timed out after {SCRIPT_TIMEOUT}s.",
                execution_time=SCRIPT_TIMEOUT,
            )
        except Exception as e:
            return GenerationResult(
                success=False,
                error=f"Execution error: {e}",
                execution_time=time.monotonic() - t0,
            )
        finally:
            # Clean up temp script
            Path(script_path).unlink(missing_ok=True)

    async def validate(self, step_path: Path) -> ValidationResult:
        """
        Validate a STEP file for solid integrity.

        Uses CadQuery to load and inspect the STEP file.
        """
        validate_code = f"""
import json
try:
    import cadquery as cq
    result = cq.importers.importStep("{step_path.as_posix()}")
    solids = result.solids().vals()
    bodies = len(solids)
    faces = sum(len(s.Faces()) for s in solids)
    volume = sum(s.Volume() for s in solids)
    bb = result.val().BoundingBox()
    print(json.dumps({{
        "valid": True,
        "body_count": bodies,
        "face_count": faces,
        "volume": volume,
        "bounding_box": {{
            "x_min": bb.xmin, "x_max": bb.xmax,
            "y_min": bb.ymin, "y_max": bb.ymax,
            "z_min": bb.zmin, "z_max": bb.zmax,
        }},
        "errors": []
    }}))
except Exception as e:
    print(json.dumps({{
        "valid": False,
        "body_count": 0, "face_count": 0, "volume": 0.0,
        "bounding_box": None,
        "errors": [str(e)]
    }}))
"""
        try:
            proc = await asyncio.create_subprocess_exec(
                "python", "-c", validate_code,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
            data = json.loads(stdout.decode("utf-8"))
            return ValidationResult(**data)
        except Exception as e:
            return ValidationResult(valid=False, errors=[str(e)])

    async def export(
        self,
        step_path: Path,
        formats: list[str],
        output_dir: Path,
    ) -> dict[str, Path]:
        """
        Export a STEP file to additional formats.

        Supported formats: stl, gltf
        """
        results = {}
        base = step_path.stem

        for fmt in formats:
            if fmt == "stl":
                stl_path = output_dir / f"{base}.stl"
                export_code = f"""
import cadquery as cq
result = cq.importers.importStep("{step_path.as_posix()}")
cq.exporters.export(result, "{stl_path.as_posix()}")
print("OK")
"""
                try:
                    proc = await asyncio.create_subprocess_exec(
                        "python", "-c", export_code,
                        stdout=asyncio.subprocess.PIPE,
                        stderr=asyncio.subprocess.PIPE,
                    )
                    await asyncio.wait_for(proc.communicate(), timeout=60)
                    if stl_path.exists():
                        results["stl"] = stl_path
                except Exception as e:
                    logger.warning("STL export failed: %s", e)

        return results

    def _wrap_script(self, code: str, step_path: str, stl_path: str) -> str:
        """
        Wrap user CAD script with export logic.

        Handles both CadQuery and build123d scripts by detecting the API used.
        """
        # Normalize path separators for Python
        step_path = step_path.replace("\\", "/")
        stl_path = stl_path.replace("\\", "/")

        return f"""\
# === User CAD Script ===
{code}
# === Auto-Export ===
import sys

# Try CadQuery export
try:
    import cadquery as cq
    if 'result' in dir() and isinstance(result, cq.Workplane):
        cq.exporters.export(result, "{step_path}")
        cq.exporters.export(result, "{stl_path}")
        print("Exported via CadQuery")
        sys.exit(0)
except (ImportError, NameError, Exception) as e:
    pass

# Try build123d export
try:
    from build123d import export_step, export_stl
    if 'result' in dir():
        export_step(result, "{step_path}")
        export_stl(result, "{stl_path}")
        print("Exported via build123d")
        sys.exit(0)
except (ImportError, NameError, Exception) as e:
    pass

# If neither worked, try to find any Part/Shape variable
try:
    import cadquery as cq
    for name, obj in list(globals().items()):
        if isinstance(obj, cq.Workplane) and name != '__builtins__':
            cq.exporters.export(obj, "{step_path}")
            cq.exporters.export(obj, "{stl_path}")
            print(f"Exported {{name}} via CadQuery")
            sys.exit(0)
except Exception:
    pass

print("WARNING: No exportable CAD object found. Define a variable named 'result'.", file=sys.stderr)
"""
